/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ControllerBarang;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import util.Koneksi;
import javax.swing.table.DefaultTableModel;
import model.ModelBarang;

/**
 *
 * @author DIKKY
 */
public class VIEWBarang extends javax.swing.JFrame {

    Koneksi DIK = new Koneksi();
    ControllerBarang CONTROL = new ControllerBarang();
    ModelBarang MODEL = new ModelBarang();

    /**
     * Creates new form ViewBarang
     */
    public VIEWBarang() {
        initComponents();
        dataTabel();
        setLocationRelativeTo(null);
    }

    private void baru() {
        jButtonBaru.setText("Batal");
        jButtonBersih.setEnabled(true);
        jButtonHapus.setEnabled(false);
        jButtonUbah.setEnabled(false);
        JbuttonSimpan.setEnabled(true);
        jTextFieldJenis.setEnabled(true);
        jTextFieldJumlah.setEnabled(true);
        jTextFieldNama.setEnabled(true);
        jTextFieldID.setText("");
        jTextFieldJenis.setText("");
         jTextFieldJumlah.setText("");
        jTextFieldNama.setText("");
    }

    private void bersih() {
        baru();
        jButtonBaru.setText("Baru");
        jButtonBersih.setEnabled(false);
        JbuttonSimpan.setEnabled(false);
        jTextFieldJenis.setEnabled(false);
        jTextFieldJumlah.setEnabled(false);
        jTextFieldNama.setEnabled(false);
    }

    private void ubahanHapus() {
        jButtonBersih.setEnabled(true);
        jButtonHapus.setEnabled(true);
        jButtonUbah.setEnabled(true);
        jTextFieldJenis.setEnabled(true);
        jTextFieldJumlah.setEnabled(true);
        jTextFieldNama.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldID = new javax.swing.JTextField();
        jTextFieldNama = new javax.swing.JTextField();
        jTextFieldJenis = new javax.swing.JTextField();
        jTextFieldJumlah = new javax.swing.JTextField();
        jButtonBaru = new javax.swing.JButton();
        jButtonUbah = new javax.swing.JButton();
        JbuttonSimpan = new javax.swing.JButton();
        jButtonHapus = new javax.swing.JButton();
        jButtonBersih = new javax.swing.JButton();
        jButtonTutup = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("id Barang");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jLabel2.setText("Jumlah Barang");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel3.setText("Nama Barang");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel4.setText("Jenis Barang");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jTextFieldID.setEnabled(false);
        getContentPane().add(jTextFieldID, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 80, -1));

        jTextFieldNama.setEnabled(false);
        getContentPane().add(jTextFieldNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 120, -1));

        jTextFieldJenis.setEnabled(false);
        getContentPane().add(jTextFieldJenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 120, -1));

        jTextFieldJumlah.setEnabled(false);
        getContentPane().add(jTextFieldJumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 120, -1));

        jButtonBaru.setText("Baru");
        jButtonBaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBaruActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBaru, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 80, -1));

        jButtonUbah.setText("Ubah");
        jButtonUbah.setEnabled(false);
        jButtonUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUbahActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonUbah, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 80, -1));

        JbuttonSimpan.setText("Simpan");
        JbuttonSimpan.setEnabled(false);
        JbuttonSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbuttonSimpanActionPerformed(evt);
            }
        });
        getContentPane().add(JbuttonSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 80, -1));

        jButtonHapus.setText("Hapus");
        jButtonHapus.setEnabled(false);
        jButtonHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHapusActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, 80, -1));

        jButtonBersih.setText("Bersih");
        jButtonBersih.setEnabled(false);
        jButtonBersih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBersihActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBersih, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 80, -1));

        jButtonTutup.setText("Tutup");
        jButtonTutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTutupActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonTutup, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, 80, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 440, 160));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dataTabel() {
        DIK.koneksiDatabase();

        DefaultTableModel tabel = new DefaultTableModel();

        tabel.addColumn("ID");
        tabel.addColumn("NAMA");
        tabel.addColumn("JENIS");
        tabel.addColumn("JUMLAH");

        jTable1.setModel(tabel);

        try {
            String data = "select * from tbl_barang";

            ResultSet res = DIK.state.executeQuery(data);
            while (res.next()) {
                tabel.addRow(new Object[]{
                    res.getString("id"),
                    res.getString("nama"),
                    res.getString("jenis"),
                    res.getString("jumlah")
                });
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Harap Masukan Data");
        }

    }
    private void jButtonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHapusActionPerformed
        // TODO add your handling code here:
        try {

            int id = Integer.parseInt(jTextFieldID.getText().trim());

            MODEL.setId(id);
            CONTROL.hapusData(MODEL);

            dataTabel();
            bersih();

        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(null, "Harap Masukan Data");
        }

    }//GEN-LAST:event_jButtonHapusActionPerformed

    private void jButtonBaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBaruActionPerformed
        // TODO add your handling code here:
        String logic = jButtonBaru.getText();
        if (logic.equals("Baru")) {
            baru();
        } else {
            bersih();
        }
    }//GEN-LAST:event_jButtonBaruActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        ubahanHapus();
        try {
            int baris = jTable1.getSelectedRow();
            jTextFieldID.setText(jTable1.getValueAt(baris, 0).toString());
            jTextFieldNama.setText(jTable1.getValueAt(baris, 1).toString());
            jTextFieldJenis.setText(jTable1.getValueAt(baris, 2).toString());
            jTextFieldJumlah.setText(jTable1.getValueAt(baris, 3).toString());

        } catch (NullPointerException e) {
            System.err.println("" + e);
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButtonBersihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBersihActionPerformed
        // TODO add your handling code here:
        bersih();
    }//GEN-LAST:event_jButtonBersihActionPerformed

    private void jButtonTutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTutupActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButtonTutupActionPerformed

    private void JbuttonSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbuttonSimpanActionPerformed
        // TODO add your handling code here:
        try {

            String nama = jTextFieldNama.getText();
            String jenis = jTextFieldJenis.getText();
            int jumlah = Integer.parseInt(jTextFieldJumlah.getText().trim());

            MODEL.setNama(nama);
            MODEL.setJenis(jenis);
            MODEL.setJumlah(jumlah);
            CONTROL.simpanData(MODEL);

            dataTabel();
            bersih();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Harap Masukan Data");
        }

    }//GEN-LAST:event_JbuttonSimpanActionPerformed

    private void jButtonUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUbahActionPerformed
        // TODO add your handling code here:
        try {
            int id = Integer.parseInt(jTextFieldID.getText());
            String nama = jTextFieldNama.getText();
            String jenis = jTextFieldJenis.getText();
            int jumlah = Integer.parseInt(jTextFieldJumlah.getText().trim());

            MODEL.setId(id);
            MODEL.setNama(nama);
            MODEL.setJenis(jenis);
            MODEL.setJumlah(jumlah);
            CONTROL.ubahData(MODEL);

            dataTabel();
            bersih();
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(null, "Harap masukan data");
        }

    }//GEN-LAST:event_jButtonUbahActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JbuttonSimpan;
    private javax.swing.JButton jButtonBaru;
    private javax.swing.JButton jButtonBersih;
    private javax.swing.JButton jButtonHapus;
    private javax.swing.JButton jButtonTutup;
    private javax.swing.JButton jButtonUbah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldID;
    private javax.swing.JTextField jTextFieldJenis;
    private javax.swing.JTextField jTextFieldJumlah;
    private javax.swing.JTextField jTextFieldNama;
    // End of variables declaration//GEN-END:variables
}
